name: Deploy Mini-App

on:
  push:
    branches: [ main ]
    paths:
      - 'mini_app/**'
      -  'db_init.py'
      - 'export_tests.py'
      - 'generate_words.py'
      - 'bot.db'
      - 'db.sqlite3'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install aiosqlite

      - name: Initialize tests database (bot.db)
        run: python db_init.py

      - name: Generate words database (db.sqlite3)
        run: python generate_words.py

      - name: Export tests to JSON
        run: python export_tests.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mini_app
          publish_branch: gh-pages